// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mid_saving.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("mid_saving.proto", fileDescriptor_262d7cf1cc6f51b8) }

var fileDescriptor_262d7cf1cc6f51b8 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6e, 0x12, 0x4f,
	0x14, 0xc7, 0xc3, 0x2f, 0xf9, 0x19, 0x33, 0x56, 0x8a, 0x43, 0x41, 0xba, 0x50, 0xd0, 0x69, 0xbd,
	0xb0, 0x09, 0x90, 0x54, 0xaf, 0x8c, 0x89, 0x11, 0x88, 0x86, 0x5a, 0x35, 0x29, 0x35, 0x8d, 0x57,
	0x66, 0xd9, 0x1d, 0x97, 0x09, 0x30, 0x4b, 0x67, 0x66, 0xdb, 0x70, 0x65, 0xd2, 0x57, 0xd0, 0x37,
	0xf3, 0x15, 0x7c, 0x0f, 0xcd, 0xfc, 0x59, 0x67, 0xa6, 0x94, 0x6a, 0xe2, 0x15, 0xc9, 0x39, 0x67,
	0xbe, 0x9f, 0xef, 0xf9, 0xb3, 0x80, 0xd2, 0x9c, 0xc4, 0x9f, 0x78, 0x78, 0x4e, 0x68, 0xd2, 0x59,
	0xb0, 0x54, 0xa4, 0xf0, 0xb6, 0xfa, 0x19, 0x67, 0x9f, 0x03, 0x90, 0x71, 0xcc, 0x74, 0x34, 0xd8,
	0x70, 0x6b, 0x82, 0x46, 0x92, 0xa6, 0xc9, 0x0c, 0x77, 0xc3, 0x05, 0xe9, 0x86, 0x94, 0xa6, 0x22,
	0x14, 0x24, 0xa5, 0x5c, 0x67, 0x0f, 0x7e, 0xde, 0x01, 0xa5, 0xb7, 0x24, 0x1e, 0xa9, 0x17, 0x23,
	0xcc, 0xce, 0x49, 0x84, 0xe1, 0x21, 0xf8, 0xff, 0x28, 0x4d, 0x08, 0x85, 0xd5, 0x4e, 0x0e, 0xe8,
	0xa8, 0xc0, 0x31, 0x3e, 0xcb, 0x30, 0x17, 0x01, 0xb4, 0xf1, 0xc3, 0xd3, 0x93, 0x93, 0x74, 0x8a,
	0x29, 0xaa, 0x5c, 0x7e, 0xff, 0xf1, 0xf5, 0xbf, 0x4d, 0x04, 0x14, 0x69, 0x26, 0xcb, 0x9f, 0x15,
	0xf6, 0xe1, 0x1c, 0x6c, 0x1c, 0xe3, 0x84, 0x70, 0x81, 0xd9, 0x07, 0x8e, 0x19, 0xdc, 0xb1, 0x4f,
	0xdd, 0x78, 0xae, 0xdc, 0x5c, 0x97, 0xe6, 0x8b, 0x94, 0x72, 0x8c, 0x9a, 0x8a, 0x52, 0x43, 0x65,
	0x45, 0x91, 0x4d, 0xf3, 0x2e, 0x33, 0x85, 0x12, 0x37, 0x05, 0x77, 0x5f, 0x63, 0xd1, 0xcf, 0x18,
	0xc3, 0x54, 0xbc, 0xf9, 0xd8, 0x87, 0x8e, 0xa0, 0x97, 0xc8, 0x81, 0xad, 0xb5, 0x79, 0x43, 0xdc,
	0x56, 0xc4, 0x32, 0x2a, 0x3a, 0xc4, 0xe9, 0x32, 0x92, 0xb0, 0xcb, 0x02, 0x80, 0xef, 0x17, 0x98,
	0xea, 0xe9, 0xf1, 0x97, 0x51, 0x94, 0x66, 0x54, 0xc0, 0x5d, 0x2b, 0xb9, 0x9a, 0xcd, 0xb9, 0x7b,
	0x37, 0x17, 0x19, 0xf8, 0x43, 0x05, 0xaf, 0xa3, 0xaa, 0x5e, 0x9f, 0xce, 0xfa, 0x1d, 0xcf, 0x00,
	0x38, 0x25, 0x62, 0x12, 0xb3, 0xf0, 0x22, 0x9c, 0xc1, 0xba, 0x95, 0xb5, 0xd1, 0x9c, 0xd9, 0xb8,
	0x3e, 0x69, 0x58, 0xbb, 0x8a, 0xb5, 0x83, 0x6a, 0x3e, 0xeb, 0xe2, 0x77, 0xa5, 0xa6, 0x15, 0x8d,
	0xc7, 0x21, 0x3d, 0xcb, 0x08, 0x5b, 0x42, 0x67, 0x80, 0x7e, 0x26, 0xa7, 0xde, 0xb7, 0x05, 0xba,
	0x4b, 0x53, 0x86, 0x1e, 0x28, 0x60, 0x80, 0x2a, 0x3e, 0x90, 0xe8, 0xe7, 0x92, 0x16, 0x83, 0x7b,
	0x23, 0x1c, 0xb2, 0x68, 0x62, 0x9e, 0xf4, 0x96, 0xc3, 0x01, 0xdc, 0xf4, 0x80, 0xc3, 0xc1, 0x7a,
	0xc0, 0x23, 0x05, 0x68, 0xa1, 0xc0, 0x07, 0x70, 0x25, 0xd9, 0x1e, 0x2f, 0xdb, 0x24, 0x96, 0x94,
	0x2f, 0xa0, 0xe1, 0x51, 0xb8, 0xc4, 0xf4, 0x43, 0x16, 0xbf, 0xcb, 0xe6, 0x63, 0xcc, 0xdc, 0xaf,
	0xc0, 0x8d, 0x07, 0xf5, 0x35, 0xdc, 0x23, 0xc2, 0x05, 0xda, 0x57, 0xec, 0x3d, 0xd4, 0x5a, 0xcf,
	0x6e, 0x47, 0x21, 0x8b, 0xcd, 0x1d, 0x55, 0xaf, 0x3a, 0x90, 0x57, 0x3f, 0x1c, 0xfc, 0x79, 0xba,
	0xff, 0x66, 0x42, 0x9e, 0xb3, 0x99, 0xc2, 0x64, 0xd5, 0xc3, 0x2b, 0x32, 0x13, 0x98, 0xc1, 0x92,
	0x45, 0xe8, 0xc8, 0xcd, 0xd0, 0x96, 0x82, 0x6e, 0xa3, 0xad, 0xeb, 0xa0, 0x92, 0xf4, 0xad, 0x00,
	0x9a, 0x1a, 0x25, 0x9b, 0xec, 0x2d, 0xf5, 0x38, 0xf3, 0xd3, 0x0f, 0x69, 0x82, 0xa1, 0x73, 0xa9,
	0xab, 0x59, 0xf7, 0x4f, 0x42, 0x12, 0xa5, 0x8a, 0xbc, 0xe7, 0xdc, 0x38, 0x7a, 0xaa, 0x1c, 0x74,
	0xd0, 0x63, 0xe7, 0x93, 0xb5, 0x3d, 0x53, 0x25, 0xd8, 0x36, 0xc6, 0xda, 0x4c, 0x4a, 0x4a, 0x5b,
	0x07, 0xa0, 0xe8, 0xba, 0x1a, 0x0e, 0xdc, 0xc6, 0xf5, 0x3a, 0x82, 0xa2, 0x1f, 0x81, 0x3d, 0x50,
	0xf3, 0xde, 0xc4, 0x7f, 0x71, 0x36, 0x57, 0x35, 0x9e, 0x83, 0x8a, 0xab, 0x91, 0xaf, 0x79, 0x00,
	0xcb, 0xab, 0xbb, 0x5f, 0x75, 0xf0, 0x02, 0x94, 0xed, 0x6b, 0xbb, 0xb3, 0x2d, 0xbf, 0xcc, 0xec,
	0x0d, 0xfa, 0x51, 0x39, 0xbc, 0xf1, 0x2d, 0x15, 0x7a, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0xc6, 0x47, 0x42, 0x5e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MidSavingServiceClient is the client API for MidSavingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MidSavingServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*JWTToken, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error)
	OpenSavingsAccount(ctx context.Context, in *OpenSavingsAccountRequest, opts ...grpc.CallOption) (*OpenSavingsAccountResponse, error)
	Withdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalResponse, error)
	AccountInquiry(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccount, error)
	SearchAccountByID(ctx context.Context, in *AccID, opts ...grpc.CallOption) (*SavingAccount, error)
	SearchAccountsByIDCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*SavingAccountList, error)
	SearchAccountsByUserID(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccountList, error)
	SearchAccountsByFilter(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SavingAccountList, error)
	SearchUserByNumberAccountRange(ctx context.Context, in *NumberAccountRange, opts ...grpc.CallOption) (*ListUserWithAccounts, error)
	SearchUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error)
	SearchUserByIdCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*User, error)
	SearchUserByAccountID(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*User, error)
	SearchUsersByFilter(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserList, error)
}

type midSavingServiceClient struct {
	cc *grpc.ClientConn
}

func NewMidSavingServiceClient(cc *grpc.ClientConn) MidSavingServiceClient {
	return &midSavingServiceClient{cc}
}

func (c *midSavingServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*JWTToken, error) {
	out := new(JWTToken)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error) {
	out := new(GetCurrentKYCResponse)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/GetCurrentKYC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) OpenSavingsAccount(ctx context.Context, in *OpenSavingsAccountRequest, opts ...grpc.CallOption) (*OpenSavingsAccountResponse, error) {
	out := new(OpenSavingsAccountResponse)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/OpenSavingsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) Withdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalResponse, error) {
	out := new(WithdrawalResponse)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/Withdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) AccountInquiry(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccount, error) {
	out := new(SavingAccount)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/AccountInquiry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchAccountByID(ctx context.Context, in *AccID, opts ...grpc.CallOption) (*SavingAccount, error) {
	out := new(SavingAccount)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchAccountByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchAccountsByIDCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*SavingAccountList, error) {
	out := new(SavingAccountList)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchAccountsByIDCardNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchAccountsByUserID(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccountList, error) {
	out := new(SavingAccountList)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchAccountsByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchAccountsByFilter(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SavingAccountList, error) {
	out := new(SavingAccountList)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchAccountsByFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchUserByNumberAccountRange(ctx context.Context, in *NumberAccountRange, opts ...grpc.CallOption) (*ListUserWithAccounts, error) {
	out := new(ListUserWithAccounts)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchUserByNumberAccountRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchUserByIdCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchUserByIdCardNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchUserByAccountID(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchUserByAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midSavingServiceClient) SearchUsersByFilter(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/protobuf.MidSavingService/SearchUsersByFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MidSavingServiceServer is the server API for MidSavingService service.
type MidSavingServiceServer interface {
	Login(context.Context, *LoginRequest) (*JWTToken, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	GetCurrentKYC(context.Context, *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error)
	OpenSavingsAccount(context.Context, *OpenSavingsAccountRequest) (*OpenSavingsAccountResponse, error)
	Withdrawal(context.Context, *WithdrawalRequest) (*WithdrawalResponse, error)
	AccountInquiry(context.Context, *AccountInquiryRequest) (*SavingAccount, error)
	SearchAccountByID(context.Context, *AccID) (*SavingAccount, error)
	SearchAccountsByIDCardNumber(context.Context, *IDCardNumber) (*SavingAccountList, error)
	SearchAccountsByUserID(context.Context, *AccountInquiryRequest) (*SavingAccountList, error)
	SearchAccountsByFilter(context.Context, *Filter) (*SavingAccountList, error)
	SearchUserByNumberAccountRange(context.Context, *NumberAccountRange) (*ListUserWithAccounts, error)
	SearchUserByID(context.Context, *UserID) (*User, error)
	SearchUserByIdCardNumber(context.Context, *IDCardNumber) (*User, error)
	SearchUserByAccountID(context.Context, *AccountID) (*User, error)
	SearchUsersByFilter(context.Context, *UserFilter) (*UserList, error)
}

// UnimplementedMidSavingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMidSavingServiceServer struct {
}

func (*UnimplementedMidSavingServiceServer) Login(ctx context.Context, req *LoginRequest) (*JWTToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedMidSavingServiceServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedMidSavingServiceServer) GetCurrentKYC(ctx context.Context, req *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentKYC not implemented")
}
func (*UnimplementedMidSavingServiceServer) OpenSavingsAccount(ctx context.Context, req *OpenSavingsAccountRequest) (*OpenSavingsAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSavingsAccount not implemented")
}
func (*UnimplementedMidSavingServiceServer) Withdrawal(ctx context.Context, req *WithdrawalRequest) (*WithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdrawal not implemented")
}
func (*UnimplementedMidSavingServiceServer) AccountInquiry(ctx context.Context, req *AccountInquiryRequest) (*SavingAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInquiry not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchAccountByID(ctx context.Context, req *AccID) (*SavingAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAccountByID not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchAccountsByIDCardNumber(ctx context.Context, req *IDCardNumber) (*SavingAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAccountsByIDCardNumber not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchAccountsByUserID(ctx context.Context, req *AccountInquiryRequest) (*SavingAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAccountsByUserID not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchAccountsByFilter(ctx context.Context, req *Filter) (*SavingAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAccountsByFilter not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchUserByNumberAccountRange(ctx context.Context, req *NumberAccountRange) (*ListUserWithAccounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByNumberAccountRange not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchUserByID(ctx context.Context, req *UserID) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByID not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchUserByIdCardNumber(ctx context.Context, req *IDCardNumber) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByIdCardNumber not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchUserByAccountID(ctx context.Context, req *AccountID) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByAccountID not implemented")
}
func (*UnimplementedMidSavingServiceServer) SearchUsersByFilter(ctx context.Context, req *UserFilter) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsersByFilter not implemented")
}

func RegisterMidSavingServiceServer(s *grpc.Server, srv MidSavingServiceServer) {
	s.RegisterService(&_MidSavingService_serviceDesc, srv)
}

func _MidSavingService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_GetCurrentKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).GetCurrentKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/GetCurrentKYC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).GetCurrentKYC(ctx, req.(*GetCurrentKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_OpenSavingsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSavingsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).OpenSavingsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/OpenSavingsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).OpenSavingsAccount(ctx, req.(*OpenSavingsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_Withdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).Withdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/Withdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).Withdrawal(ctx, req.(*WithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_AccountInquiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).AccountInquiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/AccountInquiry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).AccountInquiry(ctx, req.(*AccountInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchAccountByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchAccountByID(ctx, req.(*AccID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchAccountsByIDCardNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDCardNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchAccountsByIDCardNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchAccountsByIDCardNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchAccountsByIDCardNumber(ctx, req.(*IDCardNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchAccountsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchAccountsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchAccountsByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchAccountsByUserID(ctx, req.(*AccountInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchAccountsByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchAccountsByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchAccountsByFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchAccountsByFilter(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchUserByNumberAccountRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberAccountRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchUserByNumberAccountRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchUserByNumberAccountRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchUserByNumberAccountRange(ctx, req.(*NumberAccountRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchUserByID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchUserByIdCardNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDCardNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchUserByIdCardNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchUserByIdCardNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchUserByIdCardNumber(ctx, req.(*IDCardNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchUserByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchUserByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchUserByAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchUserByAccountID(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidSavingService_SearchUsersByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidSavingServiceServer).SearchUsersByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MidSavingService/SearchUsersByFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidSavingServiceServer).SearchUsersByFilter(ctx, req.(*UserFilter))
	}
	return interceptor(ctx, in, info, handler)
}

var _MidSavingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.MidSavingService",
	HandlerType: (*MidSavingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MidSavingService_Login_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _MidSavingService_RegisterUser_Handler,
		},
		{
			MethodName: "GetCurrentKYC",
			Handler:    _MidSavingService_GetCurrentKYC_Handler,
		},
		{
			MethodName: "OpenSavingsAccount",
			Handler:    _MidSavingService_OpenSavingsAccount_Handler,
		},
		{
			MethodName: "Withdrawal",
			Handler:    _MidSavingService_Withdrawal_Handler,
		},
		{
			MethodName: "AccountInquiry",
			Handler:    _MidSavingService_AccountInquiry_Handler,
		},
		{
			MethodName: "SearchAccountByID",
			Handler:    _MidSavingService_SearchAccountByID_Handler,
		},
		{
			MethodName: "SearchAccountsByIDCardNumber",
			Handler:    _MidSavingService_SearchAccountsByIDCardNumber_Handler,
		},
		{
			MethodName: "SearchAccountsByUserID",
			Handler:    _MidSavingService_SearchAccountsByUserID_Handler,
		},
		{
			MethodName: "SearchAccountsByFilter",
			Handler:    _MidSavingService_SearchAccountsByFilter_Handler,
		},
		{
			MethodName: "SearchUserByNumberAccountRange",
			Handler:    _MidSavingService_SearchUserByNumberAccountRange_Handler,
		},
		{
			MethodName: "SearchUserByID",
			Handler:    _MidSavingService_SearchUserByID_Handler,
		},
		{
			MethodName: "SearchUserByIdCardNumber",
			Handler:    _MidSavingService_SearchUserByIdCardNumber_Handler,
		},
		{
			MethodName: "SearchUserByAccountID",
			Handler:    _MidSavingService_SearchUserByAccountID_Handler,
		},
		{
			MethodName: "SearchUsersByFilter",
			Handler:    _MidSavingService_SearchUsersByFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mid_saving.proto",
}
