// Code generated by MockGen. DO NOT EDIT.
// Source: mid_saving.pb.go

// Package protobuf is a generated GoMock package.
package protobuf

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockMidSavingServiceClient is a mock of MidSavingServiceClient interface.
type MockMidSavingServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMidSavingServiceClientMockRecorder
}

// MockMidSavingServiceClientMockRecorder is the mock recorder for MockMidSavingServiceClient.
type MockMidSavingServiceClientMockRecorder struct {
	mock *MockMidSavingServiceClient
}

// NewMockMidSavingServiceClient creates a new mock instance.
func NewMockMidSavingServiceClient(ctrl *gomock.Controller) *MockMidSavingServiceClient {
	mock := &MockMidSavingServiceClient{ctrl: ctrl}
	mock.recorder = &MockMidSavingServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMidSavingServiceClient) EXPECT() *MockMidSavingServiceClientMockRecorder {
	return m.recorder
}

// AccountInquiry mocks base method.
func (m *MockMidSavingServiceClient) AccountInquiry(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccount, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AccountInquiry", varargs...)
	ret0, _ := ret[0].(*SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountInquiry indicates an expected call of AccountInquiry.
func (mr *MockMidSavingServiceClientMockRecorder) AccountInquiry(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountInquiry", reflect.TypeOf((*MockMidSavingServiceClient)(nil).AccountInquiry), varargs...)
}

// GetCurrentKYC mocks base method.
func (m *MockMidSavingServiceClient) GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCurrentKYC", varargs...)
	ret0, _ := ret[0].(*GetCurrentKYCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentKYC indicates an expected call of GetCurrentKYC.
func (mr *MockMidSavingServiceClientMockRecorder) GetCurrentKYC(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentKYC", reflect.TypeOf((*MockMidSavingServiceClient)(nil).GetCurrentKYC), varargs...)
}

// OpenSavingsAccount mocks base method.
func (m *MockMidSavingServiceClient) OpenSavingsAccount(ctx context.Context, in *OpenSavingsAccountRequest, opts ...grpc.CallOption) (*OpenSavingsAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OpenSavingsAccount", varargs...)
	ret0, _ := ret[0].(*OpenSavingsAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenSavingsAccount indicates an expected call of OpenSavingsAccount.
func (mr *MockMidSavingServiceClientMockRecorder) OpenSavingsAccount(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSavingsAccount", reflect.TypeOf((*MockMidSavingServiceClient)(nil).OpenSavingsAccount), varargs...)
}

// RegisterUser mocks base method.
func (m *MockMidSavingServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterUser", varargs...)
	ret0, _ := ret[0].(*RegisterUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockMidSavingServiceClientMockRecorder) RegisterUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockMidSavingServiceClient)(nil).RegisterUser), varargs...)
}

// SearchAccountByID mocks base method.
func (m *MockMidSavingServiceClient) SearchAccountByID(ctx context.Context, in *AccID, opts ...grpc.CallOption) (*SavingAccount, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchAccountByID", varargs...)
	ret0, _ := ret[0].(*SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountByID indicates an expected call of SearchAccountByID.
func (mr *MockMidSavingServiceClientMockRecorder) SearchAccountByID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountByID", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchAccountByID), varargs...)
}

// SearchAccountsByFilter mocks base method.
func (m *MockMidSavingServiceClient) SearchAccountsByFilter(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SavingAccountList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchAccountsByFilter", varargs...)
	ret0, _ := ret[0].(*SavingAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountsByFilter indicates an expected call of SearchAccountsByFilter.
func (mr *MockMidSavingServiceClientMockRecorder) SearchAccountsByFilter(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountsByFilter", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchAccountsByFilter), varargs...)
}

// SearchAccountsByIDCardNumber mocks base method.
func (m *MockMidSavingServiceClient) SearchAccountsByIDCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*SavingAccountList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchAccountsByIDCardNumber", varargs...)
	ret0, _ := ret[0].(*SavingAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountsByIDCardNumber indicates an expected call of SearchAccountsByIDCardNumber.
func (mr *MockMidSavingServiceClientMockRecorder) SearchAccountsByIDCardNumber(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountsByIDCardNumber", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchAccountsByIDCardNumber), varargs...)
}

// SearchAccountsByUserID mocks base method.
func (m *MockMidSavingServiceClient) SearchAccountsByUserID(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccountList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchAccountsByUserID", varargs...)
	ret0, _ := ret[0].(*SavingAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountsByUserID indicates an expected call of SearchAccountsByUserID.
func (mr *MockMidSavingServiceClientMockRecorder) SearchAccountsByUserID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountsByUserID", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchAccountsByUserID), varargs...)
}

// SearchUserByAccountID mocks base method.
func (m *MockMidSavingServiceClient) SearchUserByAccountID(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchUserByAccountID", varargs...)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUserByAccountID indicates an expected call of SearchUserByAccountID.
func (mr *MockMidSavingServiceClientMockRecorder) SearchUserByAccountID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUserByAccountID", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchUserByAccountID), varargs...)
}

// SearchUserByID mocks base method.
func (m *MockMidSavingServiceClient) SearchUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchUserByID", varargs...)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUserByID indicates an expected call of SearchUserByID.
func (mr *MockMidSavingServiceClientMockRecorder) SearchUserByID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUserByID", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchUserByID), varargs...)
}

// SearchUserByIdCardNumber mocks base method.
func (m *MockMidSavingServiceClient) SearchUserByIdCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchUserByIdCardNumber", varargs...)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUserByIdCardNumber indicates an expected call of SearchUserByIdCardNumber.
func (mr *MockMidSavingServiceClientMockRecorder) SearchUserByIdCardNumber(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUserByIdCardNumber", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchUserByIdCardNumber), varargs...)
}

// SearchUsersByFilter mocks base method.
func (m *MockMidSavingServiceClient) SearchUsersByFilter(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchUsersByFilter", varargs...)
	ret0, _ := ret[0].(*UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByFilter indicates an expected call of SearchUsersByFilter.
func (mr *MockMidSavingServiceClientMockRecorder) SearchUsersByFilter(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByFilter", reflect.TypeOf((*MockMidSavingServiceClient)(nil).SearchUsersByFilter), varargs...)
}

// Withdrawal mocks base method.
func (m *MockMidSavingServiceClient) Withdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Withdrawal", varargs...)
	ret0, _ := ret[0].(*WithdrawalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdrawal indicates an expected call of Withdrawal.
func (mr *MockMidSavingServiceClientMockRecorder) Withdrawal(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawal", reflect.TypeOf((*MockMidSavingServiceClient)(nil).Withdrawal), varargs...)
}

// MockMidSavingServiceServer is a mock of MidSavingServiceServer interface.
type MockMidSavingServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockMidSavingServiceServerMockRecorder
}

// MockMidSavingServiceServerMockRecorder is the mock recorder for MockMidSavingServiceServer.
type MockMidSavingServiceServerMockRecorder struct {
	mock *MockMidSavingServiceServer
}

// NewMockMidSavingServiceServer creates a new mock instance.
func NewMockMidSavingServiceServer(ctrl *gomock.Controller) *MockMidSavingServiceServer {
	mock := &MockMidSavingServiceServer{ctrl: ctrl}
	mock.recorder = &MockMidSavingServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMidSavingServiceServer) EXPECT() *MockMidSavingServiceServerMockRecorder {
	return m.recorder
}

// AccountInquiry mocks base method.
func (m *MockMidSavingServiceServer) AccountInquiry(arg0 context.Context, arg1 *AccountInquiryRequest) (*SavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountInquiry", arg0, arg1)
	ret0, _ := ret[0].(*SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountInquiry indicates an expected call of AccountInquiry.
func (mr *MockMidSavingServiceServerMockRecorder) AccountInquiry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountInquiry", reflect.TypeOf((*MockMidSavingServiceServer)(nil).AccountInquiry), arg0, arg1)
}

// GetCurrentKYC mocks base method.
func (m *MockMidSavingServiceServer) GetCurrentKYC(arg0 context.Context, arg1 *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentKYC", arg0, arg1)
	ret0, _ := ret[0].(*GetCurrentKYCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentKYC indicates an expected call of GetCurrentKYC.
func (mr *MockMidSavingServiceServerMockRecorder) GetCurrentKYC(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentKYC", reflect.TypeOf((*MockMidSavingServiceServer)(nil).GetCurrentKYC), arg0, arg1)
}

// OpenSavingsAccount mocks base method.
func (m *MockMidSavingServiceServer) OpenSavingsAccount(arg0 context.Context, arg1 *OpenSavingsAccountRequest) (*OpenSavingsAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSavingsAccount", arg0, arg1)
	ret0, _ := ret[0].(*OpenSavingsAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenSavingsAccount indicates an expected call of OpenSavingsAccount.
func (mr *MockMidSavingServiceServerMockRecorder) OpenSavingsAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSavingsAccount", reflect.TypeOf((*MockMidSavingServiceServer)(nil).OpenSavingsAccount), arg0, arg1)
}

// RegisterUser mocks base method.
func (m *MockMidSavingServiceServer) RegisterUser(arg0 context.Context, arg1 *RegisterUserRequest) (*RegisterUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0, arg1)
	ret0, _ := ret[0].(*RegisterUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockMidSavingServiceServerMockRecorder) RegisterUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockMidSavingServiceServer)(nil).RegisterUser), arg0, arg1)
}

// SearchAccountByID mocks base method.
func (m *MockMidSavingServiceServer) SearchAccountByID(arg0 context.Context, arg1 *AccID) (*SavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountByID", arg0, arg1)
	ret0, _ := ret[0].(*SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountByID indicates an expected call of SearchAccountByID.
func (mr *MockMidSavingServiceServerMockRecorder) SearchAccountByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountByID", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchAccountByID), arg0, arg1)
}

// SearchAccountsByFilter mocks base method.
func (m *MockMidSavingServiceServer) SearchAccountsByFilter(arg0 context.Context, arg1 *Filter) (*SavingAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountsByFilter", arg0, arg1)
	ret0, _ := ret[0].(*SavingAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountsByFilter indicates an expected call of SearchAccountsByFilter.
func (mr *MockMidSavingServiceServerMockRecorder) SearchAccountsByFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountsByFilter", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchAccountsByFilter), arg0, arg1)
}

// SearchAccountsByIDCardNumber mocks base method.
func (m *MockMidSavingServiceServer) SearchAccountsByIDCardNumber(arg0 context.Context, arg1 *IDCardNumber) (*SavingAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountsByIDCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*SavingAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountsByIDCardNumber indicates an expected call of SearchAccountsByIDCardNumber.
func (mr *MockMidSavingServiceServerMockRecorder) SearchAccountsByIDCardNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountsByIDCardNumber", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchAccountsByIDCardNumber), arg0, arg1)
}

// SearchAccountsByUserID mocks base method.
func (m *MockMidSavingServiceServer) SearchAccountsByUserID(arg0 context.Context, arg1 *AccountInquiryRequest) (*SavingAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAccountsByUserID", arg0, arg1)
	ret0, _ := ret[0].(*SavingAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAccountsByUserID indicates an expected call of SearchAccountsByUserID.
func (mr *MockMidSavingServiceServerMockRecorder) SearchAccountsByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAccountsByUserID", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchAccountsByUserID), arg0, arg1)
}

// SearchUserByAccountID mocks base method.
func (m *MockMidSavingServiceServer) SearchUserByAccountID(arg0 context.Context, arg1 *AccountID) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUserByAccountID", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUserByAccountID indicates an expected call of SearchUserByAccountID.
func (mr *MockMidSavingServiceServerMockRecorder) SearchUserByAccountID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUserByAccountID", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchUserByAccountID), arg0, arg1)
}

// SearchUserByID mocks base method.
func (m *MockMidSavingServiceServer) SearchUserByID(arg0 context.Context, arg1 *UserID) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUserByID", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUserByID indicates an expected call of SearchUserByID.
func (mr *MockMidSavingServiceServerMockRecorder) SearchUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUserByID", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchUserByID), arg0, arg1)
}

// SearchUserByIdCardNumber mocks base method.
func (m *MockMidSavingServiceServer) SearchUserByIdCardNumber(arg0 context.Context, arg1 *IDCardNumber) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUserByIdCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUserByIdCardNumber indicates an expected call of SearchUserByIdCardNumber.
func (mr *MockMidSavingServiceServerMockRecorder) SearchUserByIdCardNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUserByIdCardNumber", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchUserByIdCardNumber), arg0, arg1)
}

// SearchUsersByFilter mocks base method.
func (m *MockMidSavingServiceServer) SearchUsersByFilter(arg0 context.Context, arg1 *UserFilter) (*UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByFilter", arg0, arg1)
	ret0, _ := ret[0].(*UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByFilter indicates an expected call of SearchUsersByFilter.
func (mr *MockMidSavingServiceServerMockRecorder) SearchUsersByFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByFilter", reflect.TypeOf((*MockMidSavingServiceServer)(nil).SearchUsersByFilter), arg0, arg1)
}

// Withdrawal mocks base method.
func (m *MockMidSavingServiceServer) Withdrawal(arg0 context.Context, arg1 *WithdrawalRequest) (*WithdrawalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawal", arg0, arg1)
	ret0, _ := ret[0].(*WithdrawalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdrawal indicates an expected call of Withdrawal.
func (mr *MockMidSavingServiceServerMockRecorder) Withdrawal(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawal", reflect.TypeOf((*MockMidSavingServiceServer)(nil).Withdrawal), arg0, arg1)
}
