// Code generated by protoc-gen-go. DO NOT EDIT.
// source: saving.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SavingAccount struct {
	// @gotags: es:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" es:"id"`
	// @gotags: es:"user_id"
	UserId string `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty" es:"user_id"`
	// @gotags: es:"balance"
	Balance  int64  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty" es:"balance"`
	TermType string `protobuf:"bytes,4,opt,name=term_type,proto3" json:"term_type,omitempty"`
	Term     int32  `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
	// @gotags: es:"term_in_days"
	TermInDays int32 `protobuf:"varint,6,opt,name=term_in_days,proto3" json:"term_in_days,omitempty" es:"term_in_days"`
	// @gotags: es:"created_date"
	CreatedDate string `protobuf:"bytes,7,opt,name=created_date,proto3" json:"created_date,omitempty" es:"created_date"`
	// @gotags: es:"due_date"
	DueDate string `protobuf:"bytes,8,opt,name=due_date,proto3" json:"due_date,omitempty" es:"due_date"`
	// @gotags: es:"rate"
	Rate float32 `protobuf:"fixed32,9,opt,name=rate,proto3" json:"rate,omitempty" es:"rate"`
	// @gotags: es:"kyc"
	Kyc                  int32    `protobuf:"varint,10,opt,name=kyc,proto3" json:"kyc,omitempty" es:"kyc"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavingAccount) Reset()         { *m = SavingAccount{} }
func (m *SavingAccount) String() string { return proto.CompactTextString(m) }
func (*SavingAccount) ProtoMessage()    {}
func (*SavingAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{0}
}

func (m *SavingAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavingAccount.Unmarshal(m, b)
}
func (m *SavingAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavingAccount.Marshal(b, m, deterministic)
}
func (m *SavingAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavingAccount.Merge(m, src)
}
func (m *SavingAccount) XXX_Size() int {
	return xxx_messageInfo_SavingAccount.Size(m)
}
func (m *SavingAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SavingAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SavingAccount proto.InternalMessageInfo

func (m *SavingAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SavingAccount) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SavingAccount) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *SavingAccount) GetTermType() string {
	if m != nil {
		return m.TermType
	}
	return ""
}

func (m *SavingAccount) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *SavingAccount) GetTermInDays() int32 {
	if m != nil {
		return m.TermInDays
	}
	return 0
}

func (m *SavingAccount) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *SavingAccount) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *SavingAccount) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *SavingAccount) GetKyc() int32 {
	if m != nil {
		return m.Kyc
	}
	return 0
}

type DeleteAccountResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{1}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AccID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccID) Reset()         { *m = AccID{} }
func (m *AccID) String() string { return proto.CompactTextString(m) }
func (*AccID) ProtoMessage()    {}
func (*AccID) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{2}
}

func (m *AccID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccID.Unmarshal(m, b)
}
func (m *AccID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccID.Marshal(b, m, deterministic)
}
func (m *AccID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccID.Merge(m, src)
}
func (m *AccID) XXX_Size() int {
	return xxx_messageInfo_AccID.Size(m)
}
func (m *AccID) XXX_DiscardUnknown() {
	xxx_messageInfo_AccID.DiscardUnknown(m)
}

var xxx_messageInfo_AccID proto.InternalMessageInfo

func (m *AccID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Filter struct {
	Kyc                  int32    `protobuf:"varint,1,opt,name=kyc,proto3" json:"kyc,omitempty"`
	TermInDays           int32    `protobuf:"varint,2,opt,name=term_in_days,proto3" json:"term_in_days,omitempty"`
	DueDateEarliest      string   `protobuf:"bytes,3,opt,name=due_date_earliest,proto3" json:"due_date_earliest,omitempty"`
	DueDateLatest        string   `protobuf:"bytes,4,opt,name=due_date_latest,proto3" json:"due_date_latest,omitempty"`
	MinBalance           int64    `protobuf:"varint,5,opt,name=min_balance,proto3" json:"min_balance,omitempty"`
	PageSize             int32    `protobuf:"varint,6,opt,name=page_size,proto3" json:"page_size,omitempty"`
	PageIndex            int32    `protobuf:"varint,7,opt,name=page_index,proto3" json:"page_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{3}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetKyc() int32 {
	if m != nil {
		return m.Kyc
	}
	return 0
}

func (m *Filter) GetTermInDays() int32 {
	if m != nil {
		return m.TermInDays
	}
	return 0
}

func (m *Filter) GetDueDateEarliest() string {
	if m != nil {
		return m.DueDateEarliest
	}
	return ""
}

func (m *Filter) GetDueDateLatest() string {
	if m != nil {
		return m.DueDateLatest
	}
	return ""
}

func (m *Filter) GetMinBalance() int64 {
	if m != nil {
		return m.MinBalance
	}
	return 0
}

func (m *Filter) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Filter) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

type SavingAccountList struct {
	AccList              []*SavingAccount `protobuf:"bytes,1,rep,name=acc_list,proto3" json:"acc_list,omitempty"`
	PageSize             int32            `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageIndex            int32            `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	AggTotalHits         int64            `protobuf:"varint,4,opt,name=agg_total_hits,json=aggTotalHits,proto3" json:"agg_total_hits,omitempty"`
	AggTotalBalance      int64            `protobuf:"varint,5,opt,name=agg_total_balance,json=aggTotalBalance,proto3" json:"agg_total_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SavingAccountList) Reset()         { *m = SavingAccountList{} }
func (m *SavingAccountList) String() string { return proto.CompactTextString(m) }
func (*SavingAccountList) ProtoMessage()    {}
func (*SavingAccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{4}
}

func (m *SavingAccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavingAccountList.Unmarshal(m, b)
}
func (m *SavingAccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavingAccountList.Marshal(b, m, deterministic)
}
func (m *SavingAccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavingAccountList.Merge(m, src)
}
func (m *SavingAccountList) XXX_Size() int {
	return xxx_messageInfo_SavingAccountList.Size(m)
}
func (m *SavingAccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_SavingAccountList.DiscardUnknown(m)
}

var xxx_messageInfo_SavingAccountList proto.InternalMessageInfo

func (m *SavingAccountList) GetAccList() []*SavingAccount {
	if m != nil {
		return m.AccList
	}
	return nil
}

func (m *SavingAccountList) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SavingAccountList) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *SavingAccountList) GetAggTotalHits() int64 {
	if m != nil {
		return m.AggTotalHits
	}
	return 0
}

func (m *SavingAccountList) GetAggTotalBalance() int64 {
	if m != nil {
		return m.AggTotalBalance
	}
	return 0
}

type OpenSavingsAccountRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	IdCardNumber         string   `protobuf:"bytes,2,opt,name=id_card_number,proto3" json:"id_card_number,omitempty"`
	Balance              int64    `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	TermType             string   `protobuf:"bytes,4,opt,name=term_type,proto3" json:"term_type,omitempty"`
	Term                 int32    `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
	CreatedDate          string   `protobuf:"bytes,6,opt,name=created_date,proto3" json:"created_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSavingsAccountRequest) Reset()         { *m = OpenSavingsAccountRequest{} }
func (m *OpenSavingsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*OpenSavingsAccountRequest) ProtoMessage()    {}
func (*OpenSavingsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{5}
}

func (m *OpenSavingsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSavingsAccountRequest.Unmarshal(m, b)
}
func (m *OpenSavingsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSavingsAccountRequest.Marshal(b, m, deterministic)
}
func (m *OpenSavingsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSavingsAccountRequest.Merge(m, src)
}
func (m *OpenSavingsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_OpenSavingsAccountRequest.Size(m)
}
func (m *OpenSavingsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSavingsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSavingsAccountRequest proto.InternalMessageInfo

func (m *OpenSavingsAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OpenSavingsAccountRequest) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *OpenSavingsAccountRequest) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *OpenSavingsAccountRequest) GetTermType() string {
	if m != nil {
		return m.TermType
	}
	return ""
}

func (m *OpenSavingsAccountRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *OpenSavingsAccountRequest) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

type OpenSavingsAccountResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=account_id,proto3" json:"account_id,omitempty"`
	Balance              int64    `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Rate                 float32  `protobuf:"fixed32,5,opt,name=rate,proto3" json:"rate,omitempty"`
	CreatedDate          string   `protobuf:"bytes,6,opt,name=created_date,proto3" json:"created_date,omitempty"`
	DueDate              string   `protobuf:"bytes,7,opt,name=due_date,proto3" json:"due_date,omitempty"`
	ExpectedInterest     int64    `protobuf:"varint,8,opt,name=expected_interest,proto3" json:"expected_interest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSavingsAccountResponse) Reset()         { *m = OpenSavingsAccountResponse{} }
func (m *OpenSavingsAccountResponse) String() string { return proto.CompactTextString(m) }
func (*OpenSavingsAccountResponse) ProtoMessage()    {}
func (*OpenSavingsAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{6}
}

func (m *OpenSavingsAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSavingsAccountResponse.Unmarshal(m, b)
}
func (m *OpenSavingsAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSavingsAccountResponse.Marshal(b, m, deterministic)
}
func (m *OpenSavingsAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSavingsAccountResponse.Merge(m, src)
}
func (m *OpenSavingsAccountResponse) XXX_Size() int {
	return xxx_messageInfo_OpenSavingsAccountResponse.Size(m)
}
func (m *OpenSavingsAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSavingsAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSavingsAccountResponse proto.InternalMessageInfo

func (m *OpenSavingsAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *OpenSavingsAccountResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OpenSavingsAccountResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *OpenSavingsAccountResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *OpenSavingsAccountResponse) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *OpenSavingsAccountResponse) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *OpenSavingsAccountResponse) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *OpenSavingsAccountResponse) GetExpectedInterest() int64 {
	if m != nil {
		return m.ExpectedInterest
	}
	return 0
}

type WithdrawalRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,proto3" json:"account_id,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Date                 string   `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawalRequest) Reset()         { *m = WithdrawalRequest{} }
func (m *WithdrawalRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawalRequest) ProtoMessage()    {}
func (*WithdrawalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{7}
}

func (m *WithdrawalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawalRequest.Unmarshal(m, b)
}
func (m *WithdrawalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawalRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawalRequest.Merge(m, src)
}
func (m *WithdrawalRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawalRequest.Size(m)
}
func (m *WithdrawalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawalRequest proto.InternalMessageInfo

func (m *WithdrawalRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *WithdrawalRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *WithdrawalRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithdrawalRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type WithdrawalResponse struct {
	Success              bool           `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Acc                  *SavingAccount `protobuf:"bytes,2,opt,name=acc,proto3" json:"acc,omitempty"`
	WithdrawnAmount      int64          `protobuf:"varint,3,opt,name=withdrawn_amount,proto3" json:"withdrawn_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WithdrawalResponse) Reset()         { *m = WithdrawalResponse{} }
func (m *WithdrawalResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawalResponse) ProtoMessage()    {}
func (*WithdrawalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{8}
}

func (m *WithdrawalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawalResponse.Unmarshal(m, b)
}
func (m *WithdrawalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawalResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawalResponse.Merge(m, src)
}
func (m *WithdrawalResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawalResponse.Size(m)
}
func (m *WithdrawalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawalResponse proto.InternalMessageInfo

func (m *WithdrawalResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *WithdrawalResponse) GetAcc() *SavingAccount {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *WithdrawalResponse) GetWithdrawnAmount() int64 {
	if m != nil {
		return m.WithdrawnAmount
	}
	return 0
}

type AccountInquiryRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInquiryRequest) Reset()         { *m = AccountInquiryRequest{} }
func (m *AccountInquiryRequest) String() string { return proto.CompactTextString(m) }
func (*AccountInquiryRequest) ProtoMessage()    {}
func (*AccountInquiryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{9}
}

func (m *AccountInquiryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInquiryRequest.Unmarshal(m, b)
}
func (m *AccountInquiryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInquiryRequest.Marshal(b, m, deterministic)
}
func (m *AccountInquiryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInquiryRequest.Merge(m, src)
}
func (m *AccountInquiryRequest) XXX_Size() int {
	return xxx_messageInfo_AccountInquiryRequest.Size(m)
}
func (m *AccountInquiryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInquiryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInquiryRequest proto.InternalMessageInfo

func (m *AccountInquiryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AccountInquiryRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type NumberAccountRange struct {
	MinNumber            int32    `protobuf:"varint,1,opt,name=min_number,proto3" json:"min_number,omitempty"`
	MaxNumber            int32    `protobuf:"varint,2,opt,name=max_number,proto3" json:"max_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberAccountRange) Reset()         { *m = NumberAccountRange{} }
func (m *NumberAccountRange) String() string { return proto.CompactTextString(m) }
func (*NumberAccountRange) ProtoMessage()    {}
func (*NumberAccountRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{10}
}

func (m *NumberAccountRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberAccountRange.Unmarshal(m, b)
}
func (m *NumberAccountRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberAccountRange.Marshal(b, m, deterministic)
}
func (m *NumberAccountRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberAccountRange.Merge(m, src)
}
func (m *NumberAccountRange) XXX_Size() int {
	return xxx_messageInfo_NumberAccountRange.Size(m)
}
func (m *NumberAccountRange) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberAccountRange.DiscardUnknown(m)
}

var xxx_messageInfo_NumberAccountRange proto.InternalMessageInfo

func (m *NumberAccountRange) GetMinNumber() int32 {
	if m != nil {
		return m.MinNumber
	}
	return 0
}

func (m *NumberAccountRange) GetMaxNumber() int32 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type UserWithAccounts struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	AccountIds           []string `protobuf:"bytes,2,rep,name=account_ids,proto3" json:"account_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserWithAccounts) Reset()         { *m = UserWithAccounts{} }
func (m *UserWithAccounts) String() string { return proto.CompactTextString(m) }
func (*UserWithAccounts) ProtoMessage()    {}
func (*UserWithAccounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{11}
}

func (m *UserWithAccounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithAccounts.Unmarshal(m, b)
}
func (m *UserWithAccounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithAccounts.Marshal(b, m, deterministic)
}
func (m *UserWithAccounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithAccounts.Merge(m, src)
}
func (m *UserWithAccounts) XXX_Size() int {
	return xxx_messageInfo_UserWithAccounts.Size(m)
}
func (m *UserWithAccounts) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithAccounts.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithAccounts proto.InternalMessageInfo

func (m *UserWithAccounts) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserWithAccounts) GetAccountIds() []string {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

type ListUserWithAccounts struct {
	UserGroup            []*UserWithAccounts `protobuf:"bytes,1,rep,name=user_group,proto3" json:"user_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListUserWithAccounts) Reset()         { *m = ListUserWithAccounts{} }
func (m *ListUserWithAccounts) String() string { return proto.CompactTextString(m) }
func (*ListUserWithAccounts) ProtoMessage()    {}
func (*ListUserWithAccounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8dd110a4bce988, []int{12}
}

func (m *ListUserWithAccounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserWithAccounts.Unmarshal(m, b)
}
func (m *ListUserWithAccounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserWithAccounts.Marshal(b, m, deterministic)
}
func (m *ListUserWithAccounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserWithAccounts.Merge(m, src)
}
func (m *ListUserWithAccounts) XXX_Size() int {
	return xxx_messageInfo_ListUserWithAccounts.Size(m)
}
func (m *ListUserWithAccounts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserWithAccounts.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserWithAccounts proto.InternalMessageInfo

func (m *ListUserWithAccounts) GetUserGroup() []*UserWithAccounts {
	if m != nil {
		return m.UserGroup
	}
	return nil
}

func init() {
	proto.RegisterType((*SavingAccount)(nil), "protobuf.SavingAccount")
	proto.RegisterType((*DeleteAccountResponse)(nil), "protobuf.DeleteAccountResponse")
	proto.RegisterType((*AccID)(nil), "protobuf.AccID")
	proto.RegisterType((*Filter)(nil), "protobuf.Filter")
	proto.RegisterType((*SavingAccountList)(nil), "protobuf.SavingAccountList")
	proto.RegisterType((*OpenSavingsAccountRequest)(nil), "protobuf.OpenSavingsAccountRequest")
	proto.RegisterType((*OpenSavingsAccountResponse)(nil), "protobuf.OpenSavingsAccountResponse")
	proto.RegisterType((*WithdrawalRequest)(nil), "protobuf.WithdrawalRequest")
	proto.RegisterType((*WithdrawalResponse)(nil), "protobuf.WithdrawalResponse")
	proto.RegisterType((*AccountInquiryRequest)(nil), "protobuf.AccountInquiryRequest")
	proto.RegisterType((*NumberAccountRange)(nil), "protobuf.NumberAccountRange")
	proto.RegisterType((*UserWithAccounts)(nil), "protobuf.UserWithAccounts")
	proto.RegisterType((*ListUserWithAccounts)(nil), "protobuf.ListUserWithAccounts")
}

func init() { proto.RegisterFile("saving.proto", fileDescriptor_7e8dd110a4bce988) }

var fileDescriptor_7e8dd110a4bce988 = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x6f, 0xe3, 0x36,
	0x10, 0x85, 0x24, 0xdb, 0xb1, 0x27, 0x59, 0x27, 0x26, 0x76, 0xbb, 0x5a, 0xef, 0x6e, 0x6a, 0x08,
	0x45, 0xe1, 0x06, 0x41, 0x80, 0x26, 0xb7, 0xdc, 0xe2, 0xba, 0x69, 0x0c, 0x14, 0x29, 0xa2, 0x24,
	0xe8, 0xa9, 0x10, 0x68, 0x8a, 0x55, 0x88, 0xca, 0xb2, 0x22, 0x52, 0x49, 0xd4, 0x7b, 0x6f, 0x05,
	0xfa, 0xcb, 0x7a, 0xed, 0x4f, 0x29, 0x7a, 0x2c, 0x48, 0x49, 0x96, 0x64, 0xf9, 0xa3, 0x40, 0xf7,
	0x64, 0xf2, 0xcd, 0x70, 0x38, 0xf3, 0x86, 0x6f, 0x2c, 0xd8, 0xe3, 0xf8, 0x89, 0x05, 0xde, 0x49,
	0x18, 0xcd, 0xc5, 0x1c, 0xb5, 0xd5, 0xcf, 0x34, 0xfe, 0xd9, 0xfa, 0x43, 0x87, 0x57, 0xb7, 0xca,
	0x74, 0x41, 0xc8, 0x3c, 0x0e, 0x04, 0xea, 0x82, 0xce, 0x5c, 0x53, 0x1b, 0x68, 0xc3, 0x8e, 0xad,
	0x33, 0x17, 0x99, 0xb0, 0x13, 0x73, 0x1a, 0x39, 0xcc, 0x35, 0x75, 0x05, 0xe6, 0x5b, 0x69, 0x99,
	0x62, 0x1f, 0x07, 0x84, 0x9a, 0xc6, 0x40, 0x1b, 0x1a, 0x76, 0xbe, 0x45, 0x1f, 0xa0, 0x23, 0x68,
	0x34, 0x73, 0x44, 0x12, 0x52, 0xb3, 0xa1, 0x4e, 0x15, 0x00, 0x42, 0xd0, 0x90, 0x1b, 0xb3, 0x39,
	0xd0, 0x86, 0x4d, 0x5b, 0xad, 0x91, 0x05, 0x7b, 0xca, 0x81, 0x05, 0x8e, 0x8b, 0x13, 0x6e, 0xb6,
	0x94, 0xad, 0x82, 0x49, 0x1f, 0x12, 0x51, 0x2c, 0xa8, 0xeb, 0xb8, 0x58, 0x50, 0x73, 0x47, 0x05,
	0xae, 0x60, 0xa8, 0x0f, 0x6d, 0x37, 0xa6, 0xa9, 0xbd, 0xad, 0xec, 0x8b, 0xbd, 0xbc, 0x37, 0x92,
	0x78, 0x67, 0xa0, 0x0d, 0x75, 0x5b, 0xad, 0xd1, 0x01, 0x18, 0xbf, 0x24, 0xc4, 0x04, 0x75, 0x9d,
	0x5c, 0x5a, 0x5f, 0xc3, 0x9b, 0x31, 0xf5, 0xa9, 0xa0, 0x19, 0x21, 0x36, 0xe5, 0xe1, 0x3c, 0xe0,
	0x54, 0x96, 0xcb, 0x63, 0x42, 0x28, 0xe7, 0x8a, 0x9d, 0xb6, 0x9d, 0x6f, 0xad, 0xb7, 0xd0, 0xbc,
	0x20, 0x64, 0x32, 0x5e, 0xe6, 0xce, 0xfa, 0x5b, 0x83, 0xd6, 0x25, 0xf3, 0x05, 0x8d, 0xf2, 0x8b,
	0xb4, 0xc5, 0x45, 0xb5, 0x92, 0xf5, 0x15, 0x25, 0x1f, 0x43, 0x2f, 0x4f, 0xdf, 0xa1, 0x38, 0xf2,
	0x19, 0xe5, 0x42, 0x91, 0xdd, 0xb1, 0xeb, 0x06, 0x34, 0x84, 0xfd, 0x05, 0xe8, 0x63, 0x21, 0x7d,
	0x53, 0xf2, 0x97, 0x61, 0x34, 0x80, 0xdd, 0x19, 0x0b, 0x9c, 0xbc, 0x7d, 0x4d, 0xd5, 0xbe, 0x32,
	0x24, 0x5b, 0x18, 0x62, 0x8f, 0x3a, 0x9c, 0xfd, 0x4a, 0xb3, 0x6e, 0x14, 0x00, 0x3a, 0x04, 0x50,
	0x1b, 0x16, 0xb8, 0xf4, 0x45, 0x35, 0xa2, 0x69, 0x97, 0x10, 0xeb, 0x2f, 0x0d, 0x7a, 0x95, 0x67,
	0xf5, 0x3d, 0xe3, 0x02, 0x9d, 0x41, 0x1b, 0x13, 0xe2, 0xf8, 0x8c, 0x0b, 0x53, 0x1b, 0x18, 0xc3,
	0xdd, 0xd3, 0xb7, 0x27, 0xf9, 0x4b, 0x3c, 0xa9, 0xb8, 0xdb, 0x0b, 0x47, 0xf4, 0xbe, 0x9c, 0x48,
	0xca, 0x51, 0x5b, 0x02, 0xb7, 0x32, 0x8f, 0x8f, 0x95, 0x3c, 0x8c, 0x22, 0xcd, 0x89, 0x04, 0xd0,
	0x17, 0xd0, 0xc5, 0x9e, 0xe7, 0x88, 0xb9, 0xc0, 0xbe, 0xf3, 0xc0, 0x04, 0x57, 0x7c, 0x18, 0xf6,
	0x1e, 0xf6, 0xbc, 0x3b, 0x09, 0x5e, 0x31, 0xc1, 0xd1, 0x11, 0xf4, 0x0a, 0xaf, 0x2a, 0x25, 0xfb,
	0xb9, 0xe3, 0x28, 0x85, 0xad, 0x3f, 0x35, 0x78, 0xf7, 0x43, 0x48, 0x83, 0x34, 0x5b, 0xbe, 0x78,
	0x23, 0x8f, 0xb1, 0xa4, 0xb5, 0xa4, 0x15, 0xad, 0xaa, 0x95, 0x2f, 0xa1, 0xcb, 0x5c, 0x87, 0xe0,
	0xc8, 0x75, 0x82, 0x78, 0x36, 0xa5, 0x51, 0x26, 0xa6, 0x25, 0xf4, 0x53, 0x6b, 0xaa, 0xa2, 0x97,
	0x56, 0x5d, 0x2f, 0xd6, 0xef, 0x3a, 0xf4, 0x57, 0xd5, 0xb3, 0xed, 0xcd, 0x6f, 0x18, 0x0b, 0x87,
	0x00, 0x38, 0x0d, 0x23, 0x8d, 0xe9, 0x63, 0x2d, 0x21, 0xe5, 0x12, 0x1b, 0xd5, 0x12, 0x73, 0x81,
	0x36, 0x4b, 0x02, 0xfd, 0x0f, 0x45, 0x54, 0x44, 0xbf, 0xb3, 0x24, 0xfa, 0x63, 0xe8, 0xd1, 0x97,
	0x90, 0x12, 0xe9, 0xcc, 0x02, 0x41, 0x23, 0xa9, 0x8a, 0xb6, 0xba, 0xb7, 0x6e, 0xb0, 0x12, 0xe8,
	0xfd, 0xc8, 0xc4, 0x83, 0x1b, 0xe1, 0x67, 0xec, 0x6f, 0xef, 0x6a, 0xb5, 0x54, 0xbd, 0x56, 0xea,
	0x67, 0xd0, 0xc2, 0x33, 0xb9, 0xc9, 0x9a, 0x99, 0xed, 0x64, 0xa1, 0x2a, 0xd9, 0xb4, 0x8d, 0x6a,
	0x6d, 0xfd, 0xa6, 0x01, 0x2a, 0xdf, 0xbd, 0xb5, 0x03, 0x5f, 0x81, 0x81, 0x09, 0x51, 0xb7, 0x6e,
	0x10, 0x92, 0xf4, 0x41, 0x47, 0x70, 0xf0, 0x9c, 0x85, 0x0e, 0x9c, 0x4a, 0x46, 0x35, 0xdc, 0xba,
	0x81, 0x37, 0xd9, 0xd9, 0x49, 0xf0, 0x18, 0xb3, 0x28, 0xf9, 0xdf, 0x34, 0x58, 0x77, 0x80, 0xae,
	0xd5, 0xf3, 0xce, 0x93, 0xc2, 0x81, 0xa7, 0x66, 0x88, 0x1c, 0x38, 0x99, 0x1c, 0xd2, 0xc1, 0x58,
	0x42, 0x94, 0x1d, 0xbf, 0x94, 0xe5, 0x22, 0xed, 0x0b, 0xc4, 0xba, 0x86, 0x83, 0x7b, 0x4e, 0x23,
	0xc9, 0x59, 0x16, 0x97, 0x6f, 0xc8, 0x71, 0x00, 0xbb, 0x45, 0x46, 0x72, 0xd8, 0x1a, 0xc3, 0x8e,
	0x5d, 0x86, 0x2c, 0x1b, 0x5e, 0xcb, 0x29, 0x55, 0x8b, 0x79, 0x0e, 0xa0, 0x82, 0x78, 0xd1, 0x3c,
	0x0e, 0xb3, 0xb9, 0xd5, 0x2f, 0xe8, 0x5e, 0xf6, 0xb7, 0x4b, 0xde, 0xa7, 0xff, 0x34, 0xa0, 0x9b,
	0x49, 0xeb, 0x96, 0x46, 0x4f, 0x8c, 0x50, 0x74, 0x09, 0xf0, 0x1d, 0x15, 0xf9, 0xbf, 0xed, 0xe7,
	0x45, 0xa0, 0x95, 0xac, 0xf7, 0xd7, 0x35, 0x16, 0x9d, 0x43, 0xb7, 0x88, 0x33, 0x4a, 0x26, 0x63,
	0xb4, 0x5f, 0x89, 0x35, 0x19, 0xaf, 0x3f, 0x7b, 0x97, 0x96, 0x9a, 0xa7, 0x3c, 0x4a, 0x64, 0x11,
	0x93, 0xf1, 0xf6, 0x6c, 0xde, 0xaf, 0x89, 0xa8, 0xc6, 0xfb, 0xb7, 0xcb, 0x51, 0xf3, 0xbf, 0xbe,
	0xe2, 0x50, 0x8a, 0x6c, 0x0e, 0xf3, 0x13, 0x7c, 0xcc, 0xfb, 0xc0, 0x47, 0xc9, 0x8a, 0x87, 0xf3,
	0xa1, 0x38, 0x5d, 0xb7, 0xf6, 0x0f, 0x0b, 0xeb, 0xca, 0x76, 0x5e, 0xc1, 0xeb, 0x6f, 0xd4, 0xf0,
	0xa8, 0x8e, 0x3c, 0xb4, 0x8e, 0xac, 0xf5, 0x2c, 0xde, 0xc0, 0xbb, 0xfb, 0x50, 0x6a, 0x77, 0xd1,
	0x84, 0x42, 0xbf, 0xa8, 0x54, 0x62, 0x6d, 0xa2, 0xac, 0x0f, 0x39, 0x81, 0x57, 0x95, 0x8f, 0x8f,
	0xf5, 0x59, 0x95, 0x5a, 0xb5, 0xf2, 0x73, 0x65, 0xda, 0x52, 0xf6, 0xb3, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x8c, 0xa3, 0x69, 0x97, 0xfa, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SavingsServiceClient is the client API for SavingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SavingsServiceClient interface {
	GetAccount(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccount, error)
	GetAccountByID(ctx context.Context, in *AccID, opts ...grpc.CallOption) (*SavingAccount, error)
	ListAccountsByUserID(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccountList, error)
	ListAccountsByFilter(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SavingAccountList, error)
	ListUsersByNumberAccountRange(ctx context.Context, in *NumberAccountRange, opts ...grpc.CallOption) (*ListUserWithAccounts, error)
	CreateSavingsAccount(ctx context.Context, in *SavingAccount, opts ...grpc.CallOption) (*SavingAccount, error)
	UpdateAccountByWithdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*SavingAccount, error)
	DeleteAccount(ctx context.Context, in *SavingAccount, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
}

type savingsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSavingsServiceClient(cc *grpc.ClientConn) SavingsServiceClient {
	return &savingsServiceClient{cc}
}

func (c *savingsServiceClient) GetAccount(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccount, error) {
	out := new(SavingAccount)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) GetAccountByID(ctx context.Context, in *AccID, opts ...grpc.CallOption) (*SavingAccount, error) {
	out := new(SavingAccount)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/GetAccountByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) ListAccountsByUserID(ctx context.Context, in *AccountInquiryRequest, opts ...grpc.CallOption) (*SavingAccountList, error) {
	out := new(SavingAccountList)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/ListAccountsByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) ListAccountsByFilter(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SavingAccountList, error) {
	out := new(SavingAccountList)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/ListAccountsByFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) ListUsersByNumberAccountRange(ctx context.Context, in *NumberAccountRange, opts ...grpc.CallOption) (*ListUserWithAccounts, error) {
	out := new(ListUserWithAccounts)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/ListUsersByNumberAccountRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) CreateSavingsAccount(ctx context.Context, in *SavingAccount, opts ...grpc.CallOption) (*SavingAccount, error) {
	out := new(SavingAccount)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/CreateSavingsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) UpdateAccountByWithdrawal(ctx context.Context, in *WithdrawalRequest, opts ...grpc.CallOption) (*SavingAccount, error) {
	out := new(SavingAccount)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/UpdateAccountByWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingsServiceClient) DeleteAccount(ctx context.Context, in *SavingAccount, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/protobuf.SavingsService/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SavingsServiceServer is the server API for SavingsService service.
type SavingsServiceServer interface {
	GetAccount(context.Context, *AccountInquiryRequest) (*SavingAccount, error)
	GetAccountByID(context.Context, *AccID) (*SavingAccount, error)
	ListAccountsByUserID(context.Context, *AccountInquiryRequest) (*SavingAccountList, error)
	ListAccountsByFilter(context.Context, *Filter) (*SavingAccountList, error)
	ListUsersByNumberAccountRange(context.Context, *NumberAccountRange) (*ListUserWithAccounts, error)
	CreateSavingsAccount(context.Context, *SavingAccount) (*SavingAccount, error)
	UpdateAccountByWithdrawal(context.Context, *WithdrawalRequest) (*SavingAccount, error)
	DeleteAccount(context.Context, *SavingAccount) (*DeleteAccountResponse, error)
}

// UnimplementedSavingsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSavingsServiceServer struct {
}

func (*UnimplementedSavingsServiceServer) GetAccount(ctx context.Context, req *AccountInquiryRequest) (*SavingAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedSavingsServiceServer) GetAccountByID(ctx context.Context, req *AccID) (*SavingAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByID not implemented")
}
func (*UnimplementedSavingsServiceServer) ListAccountsByUserID(ctx context.Context, req *AccountInquiryRequest) (*SavingAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccountsByUserID not implemented")
}
func (*UnimplementedSavingsServiceServer) ListAccountsByFilter(ctx context.Context, req *Filter) (*SavingAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccountsByFilter not implemented")
}
func (*UnimplementedSavingsServiceServer) ListUsersByNumberAccountRange(ctx context.Context, req *NumberAccountRange) (*ListUserWithAccounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsersByNumberAccountRange not implemented")
}
func (*UnimplementedSavingsServiceServer) CreateSavingsAccount(ctx context.Context, req *SavingAccount) (*SavingAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSavingsAccount not implemented")
}
func (*UnimplementedSavingsServiceServer) UpdateAccountByWithdrawal(ctx context.Context, req *WithdrawalRequest) (*SavingAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountByWithdrawal not implemented")
}
func (*UnimplementedSavingsServiceServer) DeleteAccount(ctx context.Context, req *SavingAccount) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}

func RegisterSavingsServiceServer(s *grpc.Server, srv SavingsServiceServer) {
	s.RegisterService(&_SavingsService_serviceDesc, srv)
}

func _SavingsService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).GetAccount(ctx, req.(*AccountInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_GetAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).GetAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/GetAccountByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).GetAccountByID(ctx, req.(*AccID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_ListAccountsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).ListAccountsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/ListAccountsByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).ListAccountsByUserID(ctx, req.(*AccountInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_ListAccountsByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).ListAccountsByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/ListAccountsByFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).ListAccountsByFilter(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_ListUsersByNumberAccountRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumberAccountRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).ListUsersByNumberAccountRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/ListUsersByNumberAccountRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).ListUsersByNumberAccountRange(ctx, req.(*NumberAccountRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_CreateSavingsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavingAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).CreateSavingsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/CreateSavingsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).CreateSavingsAccount(ctx, req.(*SavingAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_UpdateAccountByWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).UpdateAccountByWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/UpdateAccountByWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).UpdateAccountByWithdrawal(ctx, req.(*WithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingsService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavingAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingsServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SavingsService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingsServiceServer).DeleteAccount(ctx, req.(*SavingAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _SavingsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.SavingsService",
	HandlerType: (*SavingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _SavingsService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccountByID",
			Handler:    _SavingsService_GetAccountByID_Handler,
		},
		{
			MethodName: "ListAccountsByUserID",
			Handler:    _SavingsService_ListAccountsByUserID_Handler,
		},
		{
			MethodName: "ListAccountsByFilter",
			Handler:    _SavingsService_ListAccountsByFilter_Handler,
		},
		{
			MethodName: "ListUsersByNumberAccountRange",
			Handler:    _SavingsService_ListUsersByNumberAccountRange_Handler,
		},
		{
			MethodName: "CreateSavingsAccount",
			Handler:    _SavingsService_CreateSavingsAccount_Handler,
		},
		{
			MethodName: "UpdateAccountByWithdrawal",
			Handler:    _SavingsService_UpdateAccountByWithdrawal_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _SavingsService_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saving.proto",
}
