// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// @gotags: es:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" es:"id"`
	// @gotags: es:"id_card_number"
	IdCardNumber string `protobuf:"bytes,2,opt,name=id_card_number,proto3" json:"id_card_number,omitempty" es:"id_card_number"`
	// @gotags: es:"user_name"
	UserName string `protobuf:"bytes,3,opt,name=user_name,proto3" json:"user_name,omitempty" es:"user_name"`
	// @gotags: es:"dob"
	Dob string `protobuf:"bytes,4,opt,name=dob,proto3" json:"dob,omitempty" es:"dob"`
	// @gotags: es:"gender"
	// 0 for male, 1 for female
	Gender int32 `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty" es:"gender"`
	// @gotags: es:"address"
	Address string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty" es:"address"`
	// @gotags: es:"phone_number"
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,proto3" json:"phone_number,omitempty" es:"phone_number"`
	// @gotags: es:"kyc_level"
	KycLevel int32 `protobuf:"varint,8,opt,name=kyc_level,proto3" json:"kyc_level,omitempty" es:"kyc_level"`
	// @gotags: es:"registered_date"
	RegisteredDate string `protobuf:"bytes,9,opt,name=registered_date,proto3" json:"registered_date,omitempty" es:"registered_date"`
	// @gotags: es:"account_list"
	AccountList          []string `protobuf:"bytes,10,rep,name=account_list,proto3" json:"account_list,omitempty" es:"account_list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *User) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetKycLevel() int32 {
	if m != nil {
		return m.KycLevel
	}
	return 0
}

func (m *User) GetRegisteredDate() string {
	if m != nil {
		return m.RegisteredDate
	}
	return ""
}

func (m *User) GetAccountList() []string {
	if m != nil {
		return m.AccountList
	}
	return nil
}

type IDCardNumber struct {
	IdCardNumber         string   `protobuf:"bytes,1,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDCardNumber) Reset()         { *m = IDCardNumber{} }
func (m *IDCardNumber) String() string { return proto.CompactTextString(m) }
func (*IDCardNumber) ProtoMessage()    {}
func (*IDCardNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *IDCardNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDCardNumber.Unmarshal(m, b)
}
func (m *IDCardNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDCardNumber.Marshal(b, m, deterministic)
}
func (m *IDCardNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDCardNumber.Merge(m, src)
}
func (m *IDCardNumber) XXX_Size() int {
	return xxx_messageInfo_IDCardNumber.Size(m)
}
func (m *IDCardNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_IDCardNumber.DiscardUnknown(m)
}

var xxx_messageInfo_IDCardNumber proto.InternalMessageInfo

func (m *IDCardNumber) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

type UserList struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=user_list,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type KYC struct {
	// @gotags: es:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty" es:"user_id"`
	// @gotags: es:"level"
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty" es:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KYC) Reset()         { *m = KYC{} }
func (m *KYC) String() string { return proto.CompactTextString(m) }
func (*KYC) ProtoMessage()    {}
func (*KYC) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *KYC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KYC.Unmarshal(m, b)
}
func (m *KYC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KYC.Marshal(b, m, deterministic)
}
func (m *KYC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KYC.Merge(m, src)
}
func (m *KYC) XXX_Size() int {
	return xxx_messageInfo_KYC.Size(m)
}
func (m *KYC) XXX_DiscardUnknown() {
	xxx_messageInfo_KYC.DiscardUnknown(m)
}

var xxx_messageInfo_KYC proto.InternalMessageInfo

func (m *KYC) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *KYC) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type UserFilter struct {
	Kyc                         int32    `protobuf:"varint,1,opt,name=kyc,proto3" json:"kyc,omitempty"`
	RegisteredDateRangeEarliest string   `protobuf:"bytes,2,opt,name=registered_date_range_earliest,proto3" json:"registered_date_range_earliest,omitempty"`
	RegisteredDateRangeLatest   string   `protobuf:"bytes,3,opt,name=registered_date_range_latest,proto3" json:"registered_date_range_latest,omitempty"`
	Gender                      int32    `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Address                     string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *UserFilter) Reset()         { *m = UserFilter{} }
func (m *UserFilter) String() string { return proto.CompactTextString(m) }
func (*UserFilter) ProtoMessage()    {}
func (*UserFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFilter.Unmarshal(m, b)
}
func (m *UserFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFilter.Marshal(b, m, deterministic)
}
func (m *UserFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFilter.Merge(m, src)
}
func (m *UserFilter) XXX_Size() int {
	return xxx_messageInfo_UserFilter.Size(m)
}
func (m *UserFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFilter.DiscardUnknown(m)
}

var xxx_messageInfo_UserFilter proto.InternalMessageInfo

func (m *UserFilter) GetKyc() int32 {
	if m != nil {
		return m.Kyc
	}
	return 0
}

func (m *UserFilter) GetRegisteredDateRangeEarliest() string {
	if m != nil {
		return m.RegisteredDateRangeEarliest
	}
	return ""
}

func (m *UserFilter) GetRegisteredDateRangeLatest() string {
	if m != nil {
		return m.RegisteredDateRangeLatest
	}
	return ""
}

func (m *UserFilter) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserFilter) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AccountID struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,json=account_id,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountID) Reset()         { *m = AccountID{} }
func (m *AccountID) String() string { return proto.CompactTextString(m) }
func (*AccountID) ProtoMessage()    {}
func (*AccountID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *AccountID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountID.Unmarshal(m, b)
}
func (m *AccountID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountID.Marshal(b, m, deterministic)
}
func (m *AccountID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountID.Merge(m, src)
}
func (m *AccountID) XXX_Size() int {
	return xxx_messageInfo_AccountID.Size(m)
}
func (m *AccountID) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountID.DiscardUnknown(m)
}

var xxx_messageInfo_AccountID proto.InternalMessageInfo

func (m *AccountID) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

type RegisterUserRequest struct {
	// @gotags: es:"id_card_number"
	IdCardNumber string `protobuf:"bytes,1,opt,name=id_card_number,proto3" json:"id_card_number,omitempty" es:"id_card_number"`
	// @gotags: es:"user_name"
	UserName string `protobuf:"bytes,2,opt,name=user_name,proto3" json:"user_name,omitempty" es:"user_name"`
	// @gotags: es:"dob"
	Dob string `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty" es:"dob"`
	// @gotags: es:"gender"
	Gender int32 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty" es:"gender"`
	// @gotags: es:"address"
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty" es:"address"`
	// @gotags: es:"phone_number"
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phone_number,proto3" json:"phone_number,omitempty" es:"phone_number"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *RegisterUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterUserRequest) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *RegisterUserRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *RegisterUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type RegisterUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,json=user_id,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetCurrentKYCRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	IdCardNumber         string   `protobuf:"bytes,2,opt,name=id_card_number,proto3" json:"id_card_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentKYCRequest) Reset()         { *m = GetCurrentKYCRequest{} }
func (m *GetCurrentKYCRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentKYCRequest) ProtoMessage()    {}
func (*GetCurrentKYCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetCurrentKYCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentKYCRequest.Unmarshal(m, b)
}
func (m *GetCurrentKYCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentKYCRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentKYCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentKYCRequest.Merge(m, src)
}
func (m *GetCurrentKYCRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentKYCRequest.Size(m)
}
func (m *GetCurrentKYCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentKYCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentKYCRequest proto.InternalMessageInfo

func (m *GetCurrentKYCRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetCurrentKYCRequest) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

type GetCurrentKYCResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	IdCardNumber         string   `protobuf:"bytes,2,opt,name=id_card_number,proto3" json:"id_card_number,omitempty"`
	KycLevel             int32    `protobuf:"varint,3,opt,name=kyc_level,proto3" json:"kyc_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentKYCResponse) Reset()         { *m = GetCurrentKYCResponse{} }
func (m *GetCurrentKYCResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentKYCResponse) ProtoMessage()    {}
func (*GetCurrentKYCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *GetCurrentKYCResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentKYCResponse.Unmarshal(m, b)
}
func (m *GetCurrentKYCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentKYCResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentKYCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentKYCResponse.Merge(m, src)
}
func (m *GetCurrentKYCResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentKYCResponse.Size(m)
}
func (m *GetCurrentKYCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentKYCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentKYCResponse proto.InternalMessageInfo

func (m *GetCurrentKYCResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetCurrentKYCResponse) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *GetCurrentKYCResponse) GetKycLevel() int32 {
	if m != nil {
		return m.KycLevel
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*IDCardNumber)(nil), "protobuf.IDCardNumber")
	proto.RegisterType((*UserList)(nil), "protobuf.UserList")
	proto.RegisterType((*KYC)(nil), "protobuf.KYC")
	proto.RegisterType((*UserFilter)(nil), "protobuf.UserFilter")
	proto.RegisterType((*AccountID)(nil), "protobuf.AccountID")
	proto.RegisterType((*RegisterUserRequest)(nil), "protobuf.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "protobuf.RegisterUserResponse")
	proto.RegisterType((*GetCurrentKYCRequest)(nil), "protobuf.GetCurrentKYCRequest")
	proto.RegisterType((*GetCurrentKYCResponse)(nil), "protobuf.GetCurrentKYCResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xef, 0x6a, 0xd3, 0x50,
	0x14, 0x27, 0x49, 0xdb, 0xb5, 0x67, 0xb5, 0xca, 0x59, 0x37, 0x43, 0xd9, 0x66, 0x09, 0x32, 0x8a,
	0x48, 0x3f, 0x4c, 0x05, 0x3f, 0x88, 0x60, 0x3b, 0x26, 0x65, 0x2a, 0x92, 0x21, 0xb8, 0x4f, 0x21,
	0xcd, 0x3d, 0x76, 0x61, 0x59, 0x52, 0x6f, 0x92, 0x49, 0xdf, 0xca, 0x77, 0xf0, 0x35, 0x7c, 0x08,
	0x1f, 0x41, 0xee, 0x4d, 0xb2, 0xfc, 0x69, 0x33, 0x07, 0x7e, 0x4a, 0xce, 0xef, 0x9e, 0x7b, 0xfe,
	0xfc, 0xce, 0xef, 0x1e, 0x80, 0x38, 0x24, 0x3e, 0x5e, 0xf2, 0x20, 0x0a, 0xb0, 0x2d, 0x3f, 0xf3,
	0xf8, 0x9b, 0xf1, 0x53, 0x85, 0xc6, 0x97, 0x90, 0x38, 0xf6, 0x40, 0x75, 0x99, 0xae, 0x0c, 0x95,
	0x51, 0xc7, 0x54, 0x5d, 0x86, 0x47, 0xd0, 0x73, 0x99, 0xe5, 0xd8, 0x9c, 0x59, 0x7e, 0x7c, 0x3d,
	0x27, 0xae, 0xab, 0xf2, 0xac, 0x82, 0xe2, 0x3e, 0x74, 0x44, 0x60, 0xcb, 0xb7, 0xaf, 0x49, 0xd7,
	0xa4, 0x4b, 0x0e, 0xe0, 0x23, 0xd0, 0x58, 0x30, 0xd7, 0x1b, 0x12, 0x17, 0xbf, 0xb8, 0x07, 0xad,
	0x05, 0xf9, 0x8c, 0xb8, 0xde, 0x1c, 0x2a, 0xa3, 0xa6, 0x99, 0x5a, 0xa8, 0xc3, 0x96, 0xcd, 0x18,
	0xa7, 0x30, 0xd4, 0x5b, 0xd2, 0x3b, 0x33, 0xd1, 0x80, 0xee, 0xf2, 0x32, 0xf0, 0x29, 0xab, 0x63,
	0x4b, 0x1e, 0x97, 0x30, 0x51, 0xc5, 0xd5, 0xca, 0xb1, 0x3c, 0xba, 0x21, 0x4f, 0x6f, 0xcb, 0xc0,
	0x39, 0x80, 0x23, 0x78, 0xc8, 0x69, 0xe1, 0x86, 0x11, 0x71, 0x62, 0x16, 0xb3, 0x23, 0xd2, 0x3b,
	0x32, 0x48, 0x15, 0x16, 0xb9, 0x6c, 0xc7, 0x09, 0x62, 0x3f, 0xb2, 0x3c, 0x37, 0x8c, 0x74, 0x18,
	0x6a, 0x22, 0x57, 0x11, 0x33, 0x5e, 0x42, 0x77, 0x76, 0x32, 0xb5, 0x39, 0xfb, 0x94, 0xe4, 0x7e,
	0xba, 0xc6, 0x54, 0xc2, 0x62, 0xd7, 0x65, 0xb9, 0x97, 0xf1, 0x1a, 0xda, 0x82, 0xe7, 0x0f, 0x6e,
	0x18, 0xe1, 0xf3, 0x94, 0x33, 0x99, 0x42, 0x19, 0x6a, 0xa3, 0xed, 0xe3, 0xde, 0x38, 0x1b, 0xc9,
	0x58, 0xb8, 0x99, 0xb9, 0x83, 0xf1, 0x0a, 0xb4, 0xb3, 0x8b, 0xa9, 0x20, 0x48, 0x62, 0xb7, 0x53,
	0xca, 0x4c, 0xec, 0x43, 0x33, 0x69, 0x5c, 0x95, 0x8d, 0x27, 0x86, 0xf1, 0x5b, 0x01, 0x10, 0xa1,
	0x4e, 0x5d, 0x2f, 0x22, 0x2e, 0x26, 0x71, 0xb5, 0x72, 0xe4, 0xd5, 0xa6, 0x29, 0x7e, 0xf1, 0x14,
	0x0e, 0x2b, 0xed, 0x5b, 0xdc, 0xf6, 0x17, 0x64, 0x91, 0xcd, 0x3d, 0x97, 0xc2, 0x28, 0x9d, 0xf8,
	0x3f, 0xbc, 0x70, 0x02, 0xfb, 0x9b, 0x3d, 0x3c, 0x3b, 0x12, 0x51, 0x12, 0x51, 0xdc, 0xe9, 0x53,
	0x50, 0x45, 0xa3, 0x4e, 0x15, 0xcd, 0x92, 0x2a, 0x8c, 0x67, 0xd0, 0x79, 0x97, 0x4c, 0x65, 0x76,
	0x82, 0x07, 0xd0, 0xb1, 0x33, 0x23, 0x65, 0x07, 0xb2, 0x99, 0xb9, 0xcc, 0xf8, 0xa5, 0xc0, 0x8e,
	0x99, 0xa6, 0x97, 0xec, 0xd2, 0xf7, 0x58, 0x64, 0x3d, 0xaa, 0x99, 0xdc, 0x9d, 0x1a, 0x57, 0x6b,
	0x34, 0xae, 0x6d, 0xd2, 0xf8, 0x3d, 0xbb, 0x59, 0xd3, 0x78, 0x6b, 0x5d, 0xe3, 0xc6, 0x0c, 0xfa,
	0xe5, 0x26, 0xc2, 0x65, 0xe0, 0x87, 0x24, 0xa2, 0x86, 0xb1, 0xe3, 0x88, 0xa8, 0xa2, 0xfc, 0xb6,
	0x99, 0x99, 0xf8, 0x18, 0x5a, 0xa2, 0xcc, 0x19, 0x4b, 0x8b, 0xce, 0x14, 0x63, 0x7c, 0x85, 0xfe,
	0x7b, 0x8a, 0xa6, 0x31, 0xe7, 0xe4, 0x47, 0x67, 0x17, 0xd3, 0x8c, 0x90, 0x7a, 0x8d, 0xdd, 0x73,
	0x1d, 0x18, 0x3f, 0x60, 0xb7, 0x12, 0x39, 0xaf, 0xf2, 0xff, 0x42, 0x97, 0xdf, 0xb8, 0x56, 0x79,
	0xe3, 0xc7, 0x7f, 0x54, 0xd8, 0x16, 0xb4, 0x9c, 0x13, 0xbf, 0x71, 0x1d, 0xc2, 0x8f, 0xd0, 0x2d,
	0xb2, 0x85, 0x07, 0xf9, 0x03, 0xdb, 0x20, 0x85, 0xc1, 0x61, 0xdd, 0x71, 0x5a, 0xfe, 0x67, 0x78,
	0x50, 0xea, 0x0b, 0x0b, 0x17, 0x36, 0x51, 0x39, 0x78, 0x52, 0x7b, 0x9e, 0x46, 0x9c, 0x80, 0x7e,
	0x4e, 0x36, 0x77, 0x2e, 0x45, 0x9e, 0xc9, 0x6a, 0x56, 0x58, 0x16, 0xb8, 0x97, 0x5f, 0x2e, 0xae,
	0x9a, 0x41, 0x65, 0x4b, 0xe0, 0x1b, 0xd8, 0x2d, 0xc6, 0xc8, 0x1f, 0xc4, 0x4e, 0xee, 0x78, 0x0b,
	0xae, 0xdd, 0x7e, 0x0b, 0x58, 0xbc, 0x9d, 0x2e, 0x8a, 0x7e, 0xd9, 0x2b, 0x41, 0x07, 0x58, 0x46,
	0xc5, 0x1a, 0x9b, 0xb7, 0x24, 0xf4, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x5d, 0x4d,
	0xcd, 0x5a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error)
	SearchUserByIdCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*User, error)
	SearchUserByAccountID(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*User, error)
	SearchUserByFilter(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserList, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error) {
	out := new(GetCurrentKYCResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/GetCurrentKYC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUserByIdCardNumber(ctx context.Context, in *IDCardNumber, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/SearchUserByIdCardNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUserByAccountID(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/SearchUserByAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUserByFilter(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/SearchUserByFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	GetCurrentKYC(context.Context, *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error)
	SearchUserByIdCardNumber(context.Context, *IDCardNumber) (*User, error)
	SearchUserByAccountID(context.Context, *AccountID) (*User, error)
	SearchUserByFilter(context.Context, *UserFilter) (*UserList, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserServiceServer) GetCurrentKYC(ctx context.Context, req *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentKYC not implemented")
}
func (*UnimplementedUserServiceServer) SearchUserByIdCardNumber(ctx context.Context, req *IDCardNumber) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByIdCardNumber not implemented")
}
func (*UnimplementedUserServiceServer) SearchUserByAccountID(ctx context.Context, req *AccountID) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByAccountID not implemented")
}
func (*UnimplementedUserServiceServer) SearchUserByFilter(ctx context.Context, req *UserFilter) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByFilter not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCurrentKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCurrentKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/GetCurrentKYC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCurrentKYC(ctx, req.(*GetCurrentKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUserByIdCardNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDCardNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUserByIdCardNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/SearchUserByIdCardNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUserByIdCardNumber(ctx, req.(*IDCardNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUserByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUserByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/SearchUserByAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUserByAccountID(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUserByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUserByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/SearchUserByFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUserByFilter(ctx, req.(*UserFilter))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "GetCurrentKYC",
			Handler:    _UserService_GetCurrentKYC_Handler,
		},
		{
			MethodName: "SearchUserByIdCardNumber",
			Handler:    _UserService_SearchUserByIdCardNumber_Handler,
		},
		{
			MethodName: "SearchUserByAccountID",
			Handler:    _UserService_SearchUserByAccountID_Handler,
		},
		{
			MethodName: "SearchUserByFilter",
			Handler:    _UserService_SearchUserByFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
