// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// @gotags: es:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" es:"id"`
	// @gotags: es:"id_card_number"
	IdCardNumber string `protobuf:"bytes,2,opt,name=id_card_number,proto3" json:"id_card_number,omitempty" es:"id_card_number"`
	// @gotags: es:"user_name"
	UserName string `protobuf:"bytes,3,opt,name=user_name,proto3" json:"user_name,omitempty" es:"user_name"`
	// @gotags: es:"dob"
	Dob string `protobuf:"bytes,4,opt,name=dob,proto3" json:"dob,omitempty" es:"dob"`
	// @gotags: es:"gender"
	// false for male, true for female
	Gender bool `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty" es:"gender"`
	// @gotags: es:"address"
	Address string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty" es:"address"`
	// @gotags: es:"phone_number"
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,proto3" json:"phone_number,omitempty" es:"phone_number"`
	// @gotags: es:"kyc_level"
	KycLevel int32 `protobuf:"varint,8,opt,name=kyc_level,proto3" json:"kyc_level,omitempty" es:"kyc_level"`
	// @gotags: es:"registered_date"
	RegisteredDate string `protobuf:"bytes,9,opt,name=registered_date,proto3" json:"registered_date,omitempty" es:"registered_date"`
	// @gotags: es:"account_list"
	AccountList          []string `protobuf:"bytes,10,rep,name=account_list,proto3" json:"account_list,omitempty" es:"account_list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *User) GetGender() bool {
	if m != nil {
		return m.Gender
	}
	return false
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetKycLevel() int32 {
	if m != nil {
		return m.KycLevel
	}
	return 0
}

func (m *User) GetRegisteredDate() string {
	if m != nil {
		return m.RegisteredDate
	}
	return ""
}

func (m *User) GetAccountList() []string {
	if m != nil {
		return m.AccountList
	}
	return nil
}

type KYC struct {
	// @gotags: es:"user_id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty" es:"user_id"`
	// @gotags: es:"level"
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty" es:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KYC) Reset()         { *m = KYC{} }
func (m *KYC) String() string { return proto.CompactTextString(m) }
func (*KYC) ProtoMessage()    {}
func (*KYC) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *KYC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KYC.Unmarshal(m, b)
}
func (m *KYC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KYC.Marshal(b, m, deterministic)
}
func (m *KYC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KYC.Merge(m, src)
}
func (m *KYC) XXX_Size() int {
	return xxx_messageInfo_KYC.Size(m)
}
func (m *KYC) XXX_DiscardUnknown() {
	xxx_messageInfo_KYC.DiscardUnknown(m)
}

var xxx_messageInfo_KYC proto.InternalMessageInfo

func (m *KYC) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *KYC) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type RegisterUserRequest struct {
	// @gotags: es:"id_card_number"
	IdCardNumber string `protobuf:"bytes,1,opt,name=id_card_number,proto3" json:"id_card_number,omitempty" es:"id_card_number"`
	// @gotags: es:"user_name"
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,proto3" json:"user_name,omitempty" es:"user_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *RegisterUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type RegisterUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,json=user_id,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetCurrentKYCRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentKYCRequest) Reset()         { *m = GetCurrentKYCRequest{} }
func (m *GetCurrentKYCRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentKYCRequest) ProtoMessage()    {}
func (*GetCurrentKYCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetCurrentKYCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentKYCRequest.Unmarshal(m, b)
}
func (m *GetCurrentKYCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentKYCRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentKYCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentKYCRequest.Merge(m, src)
}
func (m *GetCurrentKYCRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentKYCRequest.Size(m)
}
func (m *GetCurrentKYCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentKYCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentKYCRequest proto.InternalMessageInfo

func (m *GetCurrentKYCRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetCurrentKYCResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	KycLevel             int32    `protobuf:"varint,2,opt,name=kyc_level,proto3" json:"kyc_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentKYCResponse) Reset()         { *m = GetCurrentKYCResponse{} }
func (m *GetCurrentKYCResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentKYCResponse) ProtoMessage()    {}
func (*GetCurrentKYCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetCurrentKYCResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentKYCResponse.Unmarshal(m, b)
}
func (m *GetCurrentKYCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentKYCResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentKYCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentKYCResponse.Merge(m, src)
}
func (m *GetCurrentKYCResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentKYCResponse.Size(m)
}
func (m *GetCurrentKYCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentKYCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentKYCResponse proto.InternalMessageInfo

func (m *GetCurrentKYCResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetCurrentKYCResponse) GetKycLevel() int32 {
	if m != nil {
		return m.KycLevel
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*KYC)(nil), "protobuf.KYC")
	proto.RegisterType((*RegisterUserRequest)(nil), "protobuf.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "protobuf.RegisterUserResponse")
	proto.RegisterType((*GetCurrentKYCRequest)(nil), "protobuf.GetCurrentKYCRequest")
	proto.RegisterType((*GetCurrentKYCResponse)(nil), "protobuf.GetCurrentKYCResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xb1, 0x9d, 0x38, 0xc9, 0x6c, 0x36, 0xbb, 0x68, 0xb3, 0xbb, 0x22, 0xf4, 0x8f, 0xf1,
	0xa1, 0xf8, 0x14, 0x4a, 0x4b, 0x9f, 0x20, 0x87, 0x12, 0x42, 0x69, 0x71, 0xe9, 0x21, 0xf4, 0x60,
	0x6c, 0x6b, 0x9a, 0x9a, 0x26, 0x76, 0x2a, 0xc9, 0x81, 0xbe, 0x54, 0xe9, 0x23, 0x16, 0x29, 0x76,
	0x13, 0x9b, 0x98, 0x9e, 0xec, 0xf9, 0x46, 0x33, 0xf3, 0x9b, 0x4f, 0x02, 0xc8, 0x05, 0xf2, 0xf1,
	0x9a, 0x67, 0x32, 0x23, 0x5d, 0xfd, 0x89, 0xf2, 0x27, 0xf7, 0xc3, 0x84, 0xd6, 0x83, 0x40, 0x4e,
	0x06, 0x60, 0x26, 0x8c, 0x1a, 0x8e, 0xe1, 0xf5, 0x7c, 0x33, 0x61, 0xe4, 0x0c, 0x06, 0x09, 0x0b,
	0xe2, 0x90, 0xb3, 0x20, 0xcd, 0x57, 0x11, 0x72, 0x6a, 0xea, 0x5c, 0x4d, 0x25, 0x47, 0xd0, 0x53,
	0x8d, 0x83, 0x34, 0x5c, 0x21, 0xb5, 0xf4, 0x91, 0x9d, 0x40, 0x7e, 0x83, 0xc5, 0xb2, 0x88, 0xb6,
	0xb4, 0xae, 0x7e, 0xc9, 0x3f, 0xb0, 0x17, 0x98, 0x32, 0xe4, 0xb4, 0xed, 0x18, 0x5e, 0xd7, 0x2f,
	0x22, 0x42, 0xa1, 0x13, 0x32, 0xc6, 0x51, 0x08, 0x6a, 0xeb, 0xd3, 0x65, 0x48, 0x5c, 0xe8, 0xaf,
	0x9f, 0xb3, 0x14, 0x4b, 0x8e, 0x8e, 0x4e, 0x57, 0x34, 0x45, 0xf1, 0xf2, 0x16, 0x07, 0x4b, 0xdc,
	0xe0, 0x92, 0x76, 0x1d, 0xc3, 0x6b, 0xfb, 0x3b, 0x81, 0x78, 0xf0, 0x8b, 0xe3, 0x22, 0x11, 0x12,
	0x39, 0xb2, 0x80, 0x85, 0x12, 0x69, 0x4f, 0x37, 0xa9, 0xcb, 0x6a, 0x56, 0x18, 0xc7, 0x59, 0x9e,
	0xca, 0x60, 0x99, 0x08, 0x49, 0xc1, 0xb1, 0xd4, 0xac, 0x7d, 0xcd, 0xbd, 0x02, 0x6b, 0x36, 0x9f,
	0x28, 0x60, 0xbd, 0xe7, 0x97, 0x6b, 0x65, 0x48, 0x86, 0xd0, 0xde, 0x82, 0x98, 0x1a, 0x64, 0x1b,
	0xb8, 0x8f, 0xf0, 0xc7, 0x2f, 0xa6, 0x29, 0xc3, 0x7d, 0x7c, 0xcd, 0x51, 0xc8, 0x03, 0x3e, 0x1b,
	0xdf, 0xfb, 0x6c, 0xd6, 0x7c, 0x76, 0xa7, 0x30, 0xac, 0x36, 0x17, 0xeb, 0x2c, 0x15, 0xa8, 0x20,
	0x45, 0x1e, 0xc7, 0xca, 0x55, 0x43, 0xdb, 0x5d, 0x86, 0xe4, 0x3f, 0xd8, 0xaa, 0x7c, 0xca, 0x8a,
	0x66, 0x25, 0xbd, 0x7b, 0x0e, 0xc3, 0x6b, 0x94, 0x93, 0x9c, 0x73, 0x4c, 0xe5, 0x6c, 0x3e, 0x29,
	0x41, 0x1b, 0xf7, 0x75, 0x6f, 0xe1, 0x6f, 0xad, 0x62, 0x37, 0xbd, 0xc1, 0xa2, 0xca, 0x7d, 0x99,
	0xb5, 0xfb, 0xba, 0x78, 0x37, 0xe0, 0x87, 0x5a, 0xe3, 0x1e, 0xf9, 0x26, 0x89, 0x91, 0xdc, 0x40,
	0x7f, 0x7f, 0x3b, 0x72, 0x3c, 0x2e, 0xdf, 0xef, 0xf8, 0x80, 0xa5, 0xa3, 0x93, 0xa6, 0x74, 0x81,
	0x75, 0x07, 0x3f, 0x2b, 0xbc, 0x64, 0xaf, 0xe0, 0xd0, 0xea, 0xa3, 0xd3, 0xc6, 0xfc, 0xb6, 0x63,
	0x64, 0xeb, 0xfc, 0xe5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x5e, 0x1c, 0x11, 0x64, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCurrentKYC(ctx context.Context, in *GetCurrentKYCRequest, opts ...grpc.CallOption) (*GetCurrentKYCResponse, error) {
	out := new(GetCurrentKYCResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/GetCurrentKYC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	GetCurrentKYC(context.Context, *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserServiceServer) GetCurrentKYC(ctx context.Context, req *GetCurrentKYCRequest) (*GetCurrentKYCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentKYC not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCurrentKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCurrentKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/GetCurrentKYC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCurrentKYC(ctx, req.(*GetCurrentKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "GetCurrentKYC",
			Handler:    _UserService_GetCurrentKYC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
